package com.probill.repository.db

import com.probill.model.Table

/**
 * Note: Change in attribute, need to change in respective Dao
 */
class DDL(val table: Table, private val queries: String) {
    override fun toString() = queries.format(table)

    companion object {
        fun queries() = listOf(
            DDL(
                Table.USERS,
                """
                CREATE TABLE %s (
                    $ID BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT by 1),
                    $CREATED_AT TIMESTAMP NOT NULL,
                    $UPDATED_AT TIMESTAMP NOT NULL,
                    $USERNAME VARCHAR(30) NOT NULL,
                    $PASSWORD VARCHAR(100), 
                    $NAME VARCHAR(30),
                    $COMPANY VARCHAR(40),
                    $ADDRESS VARCHAR(50),
                    $PHONE VARCHAR(15),
                    $GST_NUMBER VARCHAR(30),
                    $SESSION VARCHAR(100), 
                    $ENABLED BOOLEAN,
                    $EXPIRY TIMESTAMP,
                    $POLLING_INTERVAL BIGINT,
                    CONSTRAINT USR_NAME_PK PRIMARY KEY ($USERNAME)
                )
                """.trimIndent()
            ),

            DDL(
                Table.ITEM,
                """
                CREATE TABLE %s (
                    $ID BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT by 1), 
                    $CREATED_AT TIMESTAMP NOT NULL,
                    $UPDATED_AT TIMESTAMP NOT NULL,
                    $NAME VARCHAR(50) NOT NULL UNIQUE,
                    $UNIT VARCHAR(4),
                    $GST FLOAT,
                    $S_GST FLOAT, 
                    $DISCOUNT FLOAT, 
                    $TOTAL_PRICE FLOAT,
                    CONSTRAINT ITM_ID_PK PRIMARY KEY ($ID)
                )
                """.trimIndent()
            ),

            DDL(
                Table.BILL,
                """
                CREATE TABLE %s (
                    $ID BIGINT GENERATED BY DEFAULT AS IDENTITY, 
                    $CREATED_AT TIMESTAMP NOT NULL,
                    $UPDATED_AT TIMESTAMP NOT NULL,
                    $CREATED_BY VARCHAR(30) NOT NULL,
                    $NAME VARCHAR(30),
                    $PHONE VARCHAR(15),
                    $ADDRESS VARCHAR(50),
                    $ESUGAM VARCHAR(20),
                    $REMARK VARCHAR(100),
                    $ITEMS VARCHAR(10000),
                    $GST FLOAT,
                    $S_GST FLOAT, 
                    $DISCOUNT FLOAT, 
                    $TOTAL_PRICE FLOAT,
                    CONSTRAINT BILL_ID_PK PRIMARY KEY ($ID),
                    CONSTRAINT CREATED_BY_FK FOREIGN KEY ($CREATED_BY) REFERENCES ${Table.USERS} ($USERNAME)
                )
                """.trimIndent()
            ),

            DDL(
                Table.BREAKUP,
                """
                CREATE TABLE %s (
                    $ID BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT by 1), 
                    $CREATED_AT TIMESTAMP NOT NULL,
                    $UPDATED_AT TIMESTAMP NOT NULL,
                    $BILL_ID BIGINT NOT NULL,
                    $ITEM_ID BIGINT NOT NULL,
                    $QUANTITY FLOAT CONSTRAINT QTY_CK CHECK ($QUANTITY >= 0.0),
                    $NAME VARCHAR(50) NOT NULL,
                    $UNIT VARCHAR(4),
                    $GST FLOAT,
                    $S_GST FLOAT,
                    $DISCOUNT FLOAT,
                    $TOTAL_PRICE FLOAT,
                    CONSTRAINT BRKUP_ID_PK PRIMARY KEY ($ID),
                    CONSTRAINT BIL_ID_FK FOREIGN KEY ($BILL_ID) REFERENCES ${Table.BILL} ($ID)
                )
                """.trimIndent()
            ),

            DDL(
                Table.INVENTORY,
                """
                CREATE TABLE %s (
                    $ID BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT by 1), 
                    $CREATED_AT TIMESTAMP NOT NULL,
                    $UPDATED_AT TIMESTAMP NOT NULL, 
                    $COUNT INT CONSTRAINT CNT_CK CHECK ($COUNT >= 0),
                    $ITEM_ID BIGINT NOT NULL,
                    CONSTRAINT INVNTRY_ID_PK PRIMARY KEY ($ID),
                    CONSTRAINT ITM_FK FOREIGN KEY ($ITEM_ID) REFERENCES ${Table.ITEM} ($ID)
                )
                """.trimIndent()
            ),

            DDL(
                Table.SETTING,
                """
                CREATE TABLE %s (
                    $ID BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT by 1),
                    $CREATED_AT TIMESTAMP NOT NULL,
                    $UPDATED_AT TIMESTAMP NOT NULL, 
                    $USERNAME VARCHAR(30) NOT NULL,
                    $BREAKUP_PER_INVOICE INT,
                    $INVOICE_PER_PAGE INT,
                    $ESUGAM_REQUIRED BOOLEAN,
                    $PRINT_SETTINGS_REQUIRED BOOLEAN DEFAULT FALSE,
                    CONSTRAINT SETTING_ID_PK PRIMARY KEY ($ID),
                    CONSTRAINT USR_NAME_FK FOREIGN KEY ($USERNAME) REFERENCES ${Table.USERS} ($USERNAME)
                )
                """.trimIndent()
            ),

            DDL(
                Table.META,
                """
                CREATE TABLE %s (
                    $ID BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT by 1),
                    $CREATED_AT TIMESTAMP NOT NULL,
                    $UPDATED_AT TIMESTAMP NOT NULL,
                    $USERNAME VARCHAR(30) NOT NULL,
                    $IS_LOGGED_IN BOOLEAN,
                    CONSTRAINT META_ID_PK PRIMARY KEY ($ID),
                    CONSTRAINT USER_NAME_FK FOREIGN KEY ($USERNAME) REFERENCES ${Table.USERS} ($USERNAME)
                )
                """.trimIndent()
            )
        )
    }
}
